"===============================================================================
" Include vimrc...
" :let my_vimrc = "/path/to/github/kitto/home/vimrc"
" :if !empty(glob(my_vimrc))
"" :   echo "source " my_vimrc
" :   execute "source " . my_vimrc
" :else
" :   echo "Cannot find file: " my_vimrc
" :endif
"
" Message from...
" * http://phuzz.org/vimrc.html
" * http://www.vim.org/scripts/script_search_results.php
" * http://archive09.linux.com/feature/120126
" * OPTION -- http://vimdoc.sourceforge.net/htmldoc/options.html
"===============================================================================
set tabstop=4       " numbers of spaces of tab character
set shiftwidth=4    " numbers of spaces to (auto)indent
set scrolloff=3     " keep 3 lines when scrolling
set nostartofline   " don't jump to first character when paging
set ruler           " show current row and column numbers
set backspace=2     " make backspace work like most other apps
set number          " line number

" set term=builtin_ansi " fix arrow keys

" Disable beep, and show visual beep instead
" http://vim.wikia.com/wiki/Disable_beeping
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Indentation settings
"set expandtab       " tabs are converted to spaces, use only when required
"set autoindent      " always set autoindenting on
"set smartindent     " smart indent
"set cindent         " cindent
set noautoindent
set nosmartindent
set nocindent

" Set status line
" http://archive09.linux.com/feature/120126
"set statusline+=%F  " Add full file path to your existing statusline
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L] 
set laststatus=2    " always show status line


" Syntax highlight setting
" colorscheme list are in "/usr/share/vim/vim*/colors"
syntax on            " syntax highlight
colorscheme evening  " vim color scheme
hi Search cterm=NONE ctermfg=yellow ctermbg=green


"autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o


" Browse compressed files automatically
" http://vim.1045645.n5.nabble.com/How-to-vim-a-class-file-in-a-jar-file-with-the-java-decompiler-executed-td1151967.html
au BufReadCmd *.jar,*.ear,*.war call zip#Browse(expand("<amatch>"))

" Set *.log to be log4j format
" http://www.vim.org/scripts/script.php?script_id=4111
autocmd BufRead,BufNewFile *.log set syntax=log4j

" Set *.gradle for groovy language
" https://gist.github.com/uarun/1123563
autocmd BufRead,BufNewFile *.gradle setf groovy

